In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

#### Importing the dataset

In [36]:
dataset=pd.read_csv('DataSet.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [37]:
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values

In [38]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [39]:
print(Y)

[1 0 1 ... 1 1 0]


#### Encoding the Categorical Data

In [40]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X2=LabelEncoder()
X[:,2]=labelencoder_X2.fit_transform(X[:,2])
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [41]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

#### Splitting the dataset into the Training and Testing Set

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

#### Feature Scaling

In [43]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

#### Initialising the ANN

In [44]:
classifier=tf.keras.models.Sequential()

#### Adding the input and the First Hidden Layer 

In [45]:
classifier.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [46]:
classifier.add(Dense(units = 6 ,activation = 'relu'))

#### Adding the Output Layer

In [47]:
classifier.add(Dense(units = 1 , activation = 'sigmoid'))

#### Compiling The ANN 

In [48]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

#### Fitting the ANN to the Training set

In [49]:
classifier.fit(X_train,Y_train,batch_size=10,epochs=100)

Epoch 1/100
800/800 [==============================] - 1s 513us/step - loss: 0.4964 - accuracy: 0.7959
Epoch 2/100
800/800 [==============================] - 0s 528us/step - loss: 0.4364 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 0s 510us/step - loss: 0.4283 - accuracy: 0.8008
Epoch 4/100
800/800 [==============================] - 0s 511us/step - loss: 0.4220 - accuracy: 0.8150
Epoch 5/100
800/800 [==============================] - 0s 553us/step - loss: 0.4168 - accuracy: 0.8225
Epoch 6/100
800/800 [==============================] - 0s 551us/step - loss: 0.4124 - accuracy: 0.8256
Epoch 7/100
800/800 [==============================] - 0s 543us/step - loss: 0.4080 - accuracy: 0.8288
Epoch 8/100
800/800 [==============================] - 0s 526us/step - loss: 0.4030 - accuracy: 0.8310
Epoch 9/100
800/800 [==============================] - 0s 533us/step - loss: 0.3955 - accuracy: 0.8391
Epoch 10/100
800/800 [==============================] - 0s 511us/step - l

800/800 [==============================] - 0s 545us/step - loss: 0.3313 - accuracy: 0.8629
Epoch 80/100
800/800 [==============================] - 0s 544us/step - loss: 0.3316 - accuracy: 0.8644
Epoch 81/100
800/800 [==============================] - 0s 539us/step - loss: 0.3313 - accuracy: 0.8637
Epoch 82/100
800/800 [==============================] - 0s 537us/step - loss: 0.3304 - accuracy: 0.8643
Epoch 83/100
800/800 [==============================] - 0s 537us/step - loss: 0.3312 - accuracy: 0.8630
Epoch 84/100
800/800 [==============================] - 0s 547us/step - loss: 0.3311 - accuracy: 0.8636
Epoch 85/100
800/800 [==============================] - 0s 518us/step - loss: 0.3310 - accuracy: 0.8640
Epoch 86/100
800/800 [==============================] - 0s 508us/step - loss: 0.3309 - accuracy: 0.8615
Epoch 87/100
800/800 [==============================] - 0s 556us/step - loss: 0.3312 - accuracy: 0.8612
Epoch 88/100
800/800 [==============================] - 0s 508us/step - loss:

#### Predicting the Test set results

In [54]:
Y_pred=classifier.predict(X_test)
Y_pred=(Y_pred>0.5)

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [59]:
new_prediction=classifier.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
new_prediction=(new_prediction>0.5)
new_prediction

array([[False]])

#### Making the Confusion Matrix

In [52]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred) 

In [53]:
cm

array([[1507,   88],
       [ 188,  217]])